import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";

// Configuration de la police DM Sans
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

// Métadonnées de l'application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Layout racine de l'application
 * Applique la police DM Sans et définit la langue en français
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={dmSans.className}
      >
        {children}
      </body>
    </html>
  );
}
